name: shard
description: "A powerful, lightweight state management solution for Flutter with built-in persistence, debounce, throttle, and seamless widget integration."
version: 2.0.0-dev.1
homepage: https://shard-68cbe.web.app
issue_tracker: https://github.com/sinan-aktepe/shard/issues
documentation: https://shard-68cbe.web.app/en/getting-started/quick-start
repository: https://github.com/sinan-aktepe/shard
topics: [shard, state-management, persistence, flutter-state, async]

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.1
